### ISSUE TITLE
Give Miles' Clothing its own item texture + new texture in general

### ISSUE THREAD

**Issue by Duzos** [Duzos/superhero#14]
sorry for the email magicmaan please dnont stcream at me gaigna im sroyr

**Comment by Magicmaan** [comment]
idek what this means. could you point out what it u want fixing / whatevs???

**Comment by Duzos** [comment]
miles hoodie item texture is just a pair of glasses rn lol and idk if you made one but i need a texture of just the hoodie off the miles hoodie skin

**Comment by Magicmaan** [comment]
no :)

**Comment by Duzos** [comment]
ok @Loqor u do it desert boy

**Comment by Magicmaan** [comment]
didn't even finish the hoodie lmao

**Comment by Magicmaan** [comment]
![image](https://github.com/Duzos/superhero/assets/38400400/f47dfa14-b733-4444-a70a-ef6705e34ab7)
hoodie lol

**Comment by Magicmaan** [comment]
![image](https://github.com/Duzos/superhero/assets/38400400/7434f457-f7af-4a16-b00f-0f87fecabd0e)
hoodie actually lol

**Comment by Duzos** [comment]
okay i'll just younk it off that skin you made then

**Comment by Duzos** [comment]
archived
