### ISSUE TITLE
Figure out how to do animations and then make them easy to do.

### ISSUE THREAD

**Issue by Duzos** [Duzos/superhero#15]
Yeah yeah geckolibs a thing but 
oh wait jarinjar
um
idk then
but i want those cool animations in the game

**Comment by Duzos** [comment]
[JarJar Geckolib](https://github.com/Duzos/superhero/commit/57b76d04ea867320f3f88dba8f93a411b8e3d0b8)

**Comment by Suff99** [comment]
do you always talk to yourself in git issues

**Comment by Duzos** [comment]
i do actually yes
this is my todo list / notebook thing so get out private only

**Comment by Suff99** [comment]
- [ ] why
- [ ] dont
- [ ] you
- [ ] do
- [ ] this
- [ ] though
- [ ] as
- [ ] one
- [ ] big
- [ ] omnibus
- [ ] issue

**Comment by Duzos** [comment]
oh a list
yawn
i like clicking the close button its more fun

**Comment by Suff99** [comment]
same

**Comment by Duzos** [comment]
nuh uh

**Comment by Duzos** [comment]
archived
