### ISSUE TITLE
i cant get spiderman to work

### ISSUE THREAD

**Issue by Jeryn99** [Duzos/superhero#18]
i installed the mod on 1.30.2 and tried to launch the spidermans
when i jump off a mountain and press space, i just fall to my death????

where is andrew garfield to save me????
where is epic phonk music when he is swinging to my location???

how can i get this????
https://youtube.com/shorts/D9c5am6fq0c?feature=share

**Comment by Duzos** [comment]
get gud
- kill yourself
- go to hell
- 1v1 hell demon master guy gamer spider man devil at swinging
- repeat until you can do that
- - ---- make your own fonky music and become the best in hell with the freshest beats

**Comment by Suff99** [comment]
i am already fresh, i am fresher than a freshman

**Comment by Duzos** [comment]
yeah but are you the evil empire laughing all the way to the bank??????????

**Comment by Suff99** [comment]
quite simply, yes

**Comment by Magicmaan** [comment]
kindly, kys

**Comment by Duzos** [comment]
archived
