### ISSUE TITLE
Iron Man's Armor clipping through the player when looked at through when players are rendered from guis

### ISSUE THREAD

**Issue by MaketendoDev** [Duzos/superhero#19]
![image](https://github.com/user-attachments/assets/37a91c72-f92f-4154-8eb9-42245c29583a)

**Comment by Duzos** [comment]
Z-Fighting with skins second layer
Could disable the second layer but i dunno if that's a good solution

**Comment by Jeryn99** [comment]
It's a good solution

**Comment by gamertron106** [comment]
yeah you wouldn't see the second layer with the suit on anyway just disable it but maybe only on body parts with an armour piece equipped so you can take your helmet off in future

**Comment by Duzos** [comment]
> It's a good solution

thank you jeryn 🙏

**Comment by Duzos** [comment]
![image](https://github.com/user-attachments/assets/8bd894f6-1774-444d-bfa1-04f3abc456e4)
nope, z-fighting is also with the first layer

**Comment by MaketendoDev** [comment]
maybe if you can't see the player in the armor why not make it invisible

**Comment by MaketendoDev** [comment]
when the armor is comming off make the player not invisible

**Comment by Duzos** [comment]
ive gotten it so that its just the legs z-fighting, so i disabled everything but the legs lol

**Comment by MaketendoDev** [comment]
lol

**Comment by Jeryn99** [comment]
What I did for bulky armors that couldn't be alerted, was disabled everything but the head - because who cares that you cannot see the limbs underneath?

**Comment by Duzos** [comment]
good point, considering the only thing youll need to see is the head and thats just if the mask pulls open

**Comment by MaketendoDev** [comment]
sikkk
