### ISSUE TITLE
Movement and flight allowed while equipping/unequipping suit

### ISSUE THREAD

**Issue by gamertron106** [Duzos/superhero#21]
https://github.com/user-attachments/assets/b281ee83-27bb-4410-8663-6f376e9d1449

While equipping/taking off mk5 you can move freely and use flight

I would suggest letting players move slowly while equipping/unequipping and making the walking animation override the suit animation so the legs move while the suit opens/closes around it

**Comment by MaketendoDev** [comment]
honestly i think that kinda cool making the players move when having the transforming anim in progress
maybe once the case dissapears in the transforming should allow player movement and when going back while moving should have a different anim making the case going into the hand but if the player is standing still it should stop any movement

**Comment by gamertron106** [comment]
yeah walking forward while the armor assembles around you would look badass asf
