### ISSUE TITLE
Forge 1.20.1 Version just doesnt work (BUG)

### ISSUE THREAD

**Issue by BasicAcorn99** [Duzos/superhero#31]
I don't know what else to say besides there isn't animation mod for forge

**Comment by MaketendoDev** [comment]
?

**Comment by MaketendoDev** [comment]
please give more information so we can help!

**Comment by BasicAcorn99** [comment]
When I try and run the forge 1.20.1 version on forge 1.20.1 it just crashes, there also isn't a animation mod which is a dependency on the fabric version. I can't find one for forge.

**Comment by BasicAcorn99** [comment]
oh wait nevermind

**Comment by MaketendoDev** [comment]
alr

**Comment by MaketendoDev** [comment]
damnit lol

**Comment by MaketendoDev** [comment]
do you have any other mods?

**Comment by BasicAcorn99** [comment]
Yea theres too many to count

**Comment by MaketendoDev** [comment]
also the forge version is outdated cuz duzos remaking it in the fabric version

**Comment by MaketendoDev** [comment]
> Yea theres too many to count

could be why since the forge version is really bad

**Comment by BasicAcorn99** [comment]
So i'm gonna try getting rid of all my other mods and see if the mod works without any other mods

**Comment by MaketendoDev** [comment]
kk

**Comment by Duzos** [comment]
the mod is for fabric
the forge version is OLD and should not be used

**Comment by Duzos** [comment]
good luck tryna get it to work
send a crash report

**Comment by BasicAcorn99** [comment]
[crash-2024-09-27_09.10.12-client.txt](https://github.com/user-attachments/files/17166914/crash-2024-09-27_09.10.12-client.txt)

**Comment by Duzos** [comment]
looks like mixin failing to work

**Comment by BasicAcorn99** [comment]
is that a mod?

**Comment by Duzos** [comment]
no it's a java thing
the crash is caused by flywheel i assume because of the line
"flywheel.mixins.json"
try removing that mod or taking the issue to them
sorry can't help more
