### ISSUE TITLE
When joining a new world the player gets stuck in thirdperson while also maybe playing the suit up anim

### ISSUE THREAD

**Issue by MaketendoDev** [Duzos/superhero#32]
![2024-09-27_17 35 33](https://github.com/user-attachments/assets/ca8f2c07-8389-4745-bb11-7c4d8a604038)

**Comment by Duzos** [comment]
brand new world yes?

**Comment by MaketendoDev** [comment]
yes

**Comment by Duzos** [comment]
and steps did you do exactly

**Comment by MaketendoDev** [comment]
just loaded in the game with no mods and  joined a world
thats it

**Comment by MaketendoDev** [comment]
by no mods i mean no other mods than anim and ur mod

**Comment by MaketendoDev** [comment]
huh for some reason a simple relaod fix it ):<

**Comment by MaketendoDev** [comment]
Ohhh damn nvm it happens when you quit the game mid transformation and load up a new world

**Comment by Duzos** [comment]
animation tracker isn't cleared on disconnect
will fix soon

**Comment by MaketendoDev** [comment]
![image](https://github.com/user-attachments/assets/7eb3b5da-0e79-4a5b-85fc-b41fb887c06c)
i'm guessing its still not working
