### ISSUE TITLE
When armor is equiped no suitcase apears for transformation

### ISSUE THREAD

**Issue by MaketendoDev** [Duzos/superhero#34]
![image](https://github.com/user-attachments/assets/457d234f-29ea-47be-a7dc-38d9d3bcd2c0)

**Comment by MaketendoDev** [comment]
it also freezes the person in place

**Comment by Duzos** [comment]
how did you get this to happen

**Comment by MaketendoDev** [comment]
just wore armor
ill retest this

**Comment by MaketendoDev** [comment]
yea

**Comment by MaketendoDev** [comment]
i also had mk5 armor in my inventory if that could help
